-- 🏏 Supabase Schema for IPL Ticket Booking Web App
-- Run this script in your Supabase SQL Editor:
-- Go to https://supabase.com/dashboard/project/bayjbyocjeewbqyihprh/sql/new

-- 1. Create the bookings table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    tickets INTEGER NOT NULL CHECK (tickets > 0),
    stand TEXT NOT NULL,
    venue TEXT NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Allow anyone (anon) to insert bookings
CREATE POLICY "Allow public booking insert"
ON public.bookings
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 4. Create Policy: Allow anyone (anon) to view booking history
CREATE POLICY "Allow public booking select"
ON public.bookings
FOR SELECT
TO anon, authenticated
USING (true);
